version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container-bottest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - mongodb-net
    volumes:
      - "./mongod.conf:/etc/mongod.conf"
      - "./data:/data/db"
    command: ["mongod", "--config", "/etc/mongod.conf"]

networks:
  mongodb-net:
    driver: bridge